# Generated by Django 5.2.4 on 2025-08-20 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='singleton',
            field=models.BooleanField(default=True),
        ),
    ]
