# Generated by Django 4.2.5 on 2025-01-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ManyToManyField(through='procurement.SupplierProduct', to='procurement.supplier'),
        ),
    ]
