# Generated by Django 4.2.5 on 2025-01-28 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_product_supplier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='supplier',
            new_name='suppliers',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_price',
        ),
    ]
