# Generated by Django 4.2.5 on 2025-01-28 04:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_rename_supplier_product_suppliers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='supplierproductprice',
            name='effective_date',
            field=models.DateField(default=datetime.date(2025, 1, 27)),
        ),
        migrations.AlterField(
            model_name='supplierproductprice',
            name='supplier_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='procurement.supplierproduct'),
        ),
    ]
