# Generated by Django 4.2.5 on 2025-01-28 05:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_alter_product_product_name_alter_supplier_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierproductprice',
            name='effective_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
