# Generated by Django 4.2.18 on 2025-02-06 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0005_alter_supplierproductprice_effective_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_product', to='procurement.product'),
        ),
    ]
