# Generated by Django 4.2.18 on 2025-03-13 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0006_alter_supplierproduct_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodReceiptNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('status', models.IntegerField(choices=[(0, 'pending'), (1, 'approved'), (2, 'rejected')])),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRequirementItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('currency', models.IntegerField(choices=[(0, 'usd'), (1, 'soles')])),
                ('purchase_requirement', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='procurement.purchaserequirement')),
                ('supplier_product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='procurement.supplierproduct')),
            ],
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='total_price',
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='currency',
            field=models.IntegerField(choices=[(0, 'usd'), (1, 'soles')], default=0),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='purchase_order_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='procurement.purchaseorder'),
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='procurement.purchaseorder'),
        ),
        migrations.AddField(
            model_name='goodreceiptnote',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='procurement.purchaseorder'),
        ),
    ]
