# Generated by Django 4.2.18 on 2025-03-17 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0009_bank_supplier_ruc_alter_supplier_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='ruc',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
