# Generated by Django 4.2.18 on 2025-03-22 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0011_alter_product_suppliers_alter_supplier_ruc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliercontact',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contacts', to='procurement.supplier'),
        ),
    ]
