# Generated by Django 4.2.18 on 2025-03-22 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0012_alter_suppliercontact_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierbankaccount',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='suppliers_banks', to='procurement.bank'),
        ),
    ]
