# Generated by Django 4.2.20 on 2025-03-25 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0013_alter_supplierbankaccount_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierbankaccount',
            name='account',
            field=models.CharField(max_length=50),
        ),
    ]
