# Generated by Django 4.2.20 on 2025-03-28 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0014_alter_supplierbankaccount_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodreceiptnote',
            name='number',
            field=models.CharField(default=''),
        ),
        migrations.CreateModel(
            name='GoodReceiptNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('good_receipt_note', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='procurement.goodreceiptnote')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='procurement.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='procurement.supplier')),
            ],
        ),
    ]
