# Generated by Django 4.2.20 on 2025-03-28 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0015_goodreceiptnote_number_goodreceiptnoteitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodreceiptnoteitem',
            name='supplier',
        ),
        migrations.AddField(
            model_name='goodreceiptnote',
            name='supplier',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='procurement.supplier'),
        ),
    ]
