# Generated by Django 4.2.20 on 2025-04-17 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0016_remove_goodreceiptnoteitem_supplier_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PurchaseRequirement',
            new_name='PurchaseRequisition',
        ),
        migrations.RenameModel(
            old_name='PurchaseRequirementItems',
            new_name='PurchaseRequisitionItems',
        ),
    ]
