# Generated by Django 4.2.23 on 2025-06-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0017_alter_supplier_address_alter_supplier_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliercontact',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='suppliercontact',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='suppliercontact',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
