# Generated by Django 4.2.23 on 2025-07-08 13:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0018_suppliercontact_email_alter_suppliercontact_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierproductprice',
            name='effective_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
