# Generated by Django 5.2.3 on 2025-08-02 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0019_alter_supplierproductprice_effective_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproductprice',
            name='currency',
            field=models.CharField(choices=[('soles', 'Soles'), ('dolares', 'Dólares')], default='soles', max_length=10),
        ),
    ]
