# Generated by Django 5.2.4 on 2025-08-04 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0020_supplierproductprice_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='currency',
            field=models.IntegerField(choices=[(0, 'usd'), (1, 'soles'), (2, 'euros')], default=0),
        ),
        migrations.AlterField(
            model_name='purchaserequirementitems',
            name='currency',
            field=models.IntegerField(choices=[(0, 'usd'), (1, 'soles'), (2, 'euros')]),
        ),
        migrations.AlterField(
            model_name='supplierproductprice',
            name='currency',
            field=models.IntegerField(choices=[(0, 'usd'), (1, 'soles'), (2, 'euros')]),
        ),
    ]
