# Generated by Django 5.2.5 on 2025-08-10 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0021_alter_purchaseorderitem_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequirement',
            name='description',
        ),
    ]
