# Generated by Django 5.2.5 on 2025-08-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0022_remove_purchaserequirement_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequirement',
            name='payment_condition',
            field=models.IntegerField(choices=[(0, 'al contado'), (1, 'credito')], default=0),
        ),
    ]
