# Generated by Django 5.2.5 on 2025-08-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0023_purchaserequirement_payment_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequirement',
            name='comments',
            field=models.TextField(default=''),
        ),
    ]
