# Generated by Django 5.2.4 on 2025-08-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0024_purchaserequirement_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequirement',
            name='shipping_condition',
            field=models.TextField(default=''),
        ),
    ]
