# Generated by Django 5.2.4 on 2025-08-12 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0025_purchaserequirement_shipping_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequirement',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='procurement.supplier'),
        ),
        migrations.AlterField(
            model_name='purchaserequirement',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
