# Generated by Django 5.2.4 on 2025-08-14 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0026_purchaserequirement_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequirement',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='purchaserequirement',
            name='shipping_condition',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='purchaserequirementitems',
            name='purchase_requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='procurement.purchaserequirement'),
        ),
        migrations.AlterField(
            model_name='suppliercontact',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='suppliercontact',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
