# Generated by Django 5.2.4 on 2025-08-19 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0030_remove_product_unit_of_measure_product_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productevents',
            name='new_value',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='productevents',
            name='old_value',
            field=models.TextField(null=True),
        ),
    ]
