# Generated by Django 5.2.4 on 2025-08-19 04:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0033_alter_product_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierproductprice',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='supplierproductprice',
            name='effective_date',
        ),
        migrations.RemoveField(
            model_name='supplierproductprice',
            name='price',
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='supplierproductprice',
            name='action',
            field=models.IntegerField(choices=[(1, 'Created'), (2, 'Updated'), (3, 'Deleted')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierproductprice',
            name='changed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierproductprice',
            name='changed_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierproductprice',
            name='field_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierproductprice',
            name='new_value',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='supplierproductprice',
            name='old_value',
            field=models.TextField(null=True),
        ),
    ]
