# Generated by Django 5.2.4 on 2025-08-19 05:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0034_remove_supplierproductprice_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SupplierProductPrice',
            new_name='SupplierProductEvent',
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='currency',
            field=models.IntegerField(choices=[(0, 'usd'), (1, 'soles'), (2, 'euros')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='unit_of_measure',
            field=models.CharField(blank=True, choices=[('unidad', 'Unidad'), ('pieza', 'Pieza'), ('paquete', 'Paquete'), ('caja', 'Caja'), ('kg', 'Kilogramo (kg)'), ('g', 'Gramo (g)'), ('lb', 'Libra (lb)'), ('l', 'Litro (L)'), ('ml', 'Mililitro (mL)'), ('m', 'Metro (m)'), ('cm', 'Centímetro (cm)'), ('mm', 'Milímetro (mm)'), ('in', 'Pulgada (in)'), ('ft', 'Pie (ft)'), ('par', 'Par'), ('juego', 'Juego/Set'), ('rollo', 'Rollo'), ('botella', 'Botella'), ('bolsa', 'Bolsa')], default='', max_length=50),
        ),
    ]
