# Generated by Django 5.2.4 on 2025-08-21 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0038_supplierevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequirementitems',
            name='unit_of_measure',
            field=models.CharField(blank=True, choices=[('', '---------'), ('unidad', 'Unidad'), ('pieza', 'Pieza'), ('paquete', 'Paquete'), ('caja', 'Caja'), ('kg', 'Kilogramo (kg)'), ('g', 'Gramo (g)'), ('lb', 'Libra (lb)'), ('l', 'Litro (L)'), ('ml', 'Mililitro (mL)'), ('m', 'Metro (m)'), ('cm', 'Centímetro (cm)'), ('mm', 'Milímetro (mm)'), ('in', 'Pulgada (in)'), ('ft', 'Pie (ft)'), ('par', 'Par'), ('juego', 'Juego/Set'), ('rollo', 'Rollo'), ('botella', 'Botella'), ('bolsa', 'Bolsa')], default='', max_length=50),
        ),
    ]
