# Generated by Django 5.2.4 on 2025-08-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0040_bank_created_by_bank_updated_by_product_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequirement',
            name='vat',
            field=models.FloatField(default=0),
        ),
    ]
